export const neu = {
  midnight: "#0F172A",
  royal: "#2563EB",
  cyan: "#06B6D4",
  bg: "#F8FAFC",
  card: "#FFFFFF",
  text: "#0F172A",
  textMuted: "#64748B",
  textLight: "#94A3B8",
  border: "#E2E8F0",
  inputBorder: "#CBD5E1",
  success: "#22C55E",
  warning: "#F59E0B",
  error: "#EF4444",
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    full: 999,
  },
  shadow: {
    card: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    elevated: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 5,
    },
    none: {
      shadowColor: "transparent",
      shadowOpacity: 0,
      elevation: 0,
    },
  },
} as const
