export const neu = {
  bg: "#E2E6EC",
  surface: "#E2E6EC",
  dark: "#B8BEC8",
  light: "#FFFFFF",
  insetBg: "#D5DAE2",
  text: "#2D3748",
  textMuted: "#7A8499",
  textLight: "#A8B0BE",
  accent: "#5B7FFF",
  radius: {
    sm: 12,
    md: 18,
    lg: 24,
    xl: 28,
    full: 999,
  },
  shadow: {
    raised: {
      lightOffset: -5,
      darkOffset: 5,
      radius: 10,
      lightOpacity: 0.8,
      darkOpacity: 0.5,
      elevation: 6,
    },
    flat: {
      lightOffset: -2,
      darkOffset: 3,
      radius: 4,
      lightOpacity: 0.7,
      darkOpacity: 0.4,
      elevation: 2,
    },
    inset: {
      darkOffset: -3,
      lightOffset: 3,
      radius: 5,
      darkOpacity: 0.4,
      lightOpacity: 0.6,
      elevation: 1,
    },
  },
} as const
